config/routes.rb
EnvironmentClassesGamification::Application.routes.draw do
  root :to => "users#show"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :problems, only: [:new, :create, :edit, :update]
  resources :answers, only: [:index, :new, :create, :edit, :update]
  resources :results, only: [:new, :create, :edit, :update]
  resources :cities, only: [:new, :create]

  get 'regras' => 'pages#regras'
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  has_many :answers

  default_scope order('ends_at ASC')

  validates :ends_at, presence: true

  def self.current
    Problem.where('ends_at >= ?', DateTime.current).first
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  load_and_authorize_resource except: :create
  before_action :set_problem, only: [:show, :edit, :update, :destroy]

  # GET /problems/new
  def new
    @problem = Problem.new
  end

  # GET /problems/1/edit
  def edit
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(problem_params)
    authorize! :create, @problem

    respond_to do |format|
      if @problem.save
        format.html { redirect_to root_path, notice: 'O problema foi criado com sucesso.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problems/1
  # PATCH/PUT /problems/1.json
  def update
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to root_path, notice: 'O problema foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_params
      params.require(:problem).permit(:text, :ends_at)
    end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_form.html.haml
= simple_form_for(@problem) do |f|
  = f.error_notification

  .form-inputs
    = f.input :text, as: :text, input_html: { class: 'input-xxlarge', rows: 6 }
    = f.input :ends_at

  .form-actions
    = f.button :submit

app/views/problems/edit.html.haml
%h1 Editando #{Problem.model_name.human.downcase}

= render 'form'

= link_to t(:back), root_path

app/views/problems/index.html.haml
%h1 Listing problems

%table
  %tr
    %th Text
    %th Ends at
    %th
    %th
    %th

  - @problems.each do |problem|
    %tr
      %td= problem.text
      %td= problem.ends_at
      %td= link_to 'Show', problem
      %td= link_to 'Edit', edit_problem_path(problem)
      %td= link_to 'Destroy', problem, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Problem', new_problem_path

app/views/problems/new.html.haml
%h1 Novo #{Problem.model_name.human.downcase}

= render 'form'

= link_to t(:back), root_path

app/views/problems/show.html.haml
%p#notice= notice

%p
  %b Text:
  = @problem.text
%p
  %b Ends at:
  = @problem.ends_at

= link_to 'Edit', edit_problem_path(@problem)
\|
= link_to 'Back', problems_path