config/routes.rb
EnvironmentClassesGamification::Application.routes.draw do
  root :to => "users#show"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :problems, only: [:new, :create, :edit, :update]
  resources :answers, only: [:index, :new, :create, :edit, :update]
  resources :results, only: [:new, :create, :edit, :update]
  resources :cities, only: [:new, :create]

  get 'regras' => 'pages#regras'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :city

  def answer_for(problem)
    return if problem.nil? || city.nil?
    city.answers.where(problem_id: problem.id).first
  end
end

app/controllers/users_controller.rb
#encoding: utf-8

class UsersController < ApplicationController

  def index
    authorize! :index, user
    @users = User.all
  end

  def show
    authorize! :show, user
    dashboard
    if current_user.admin?
      admin_dashboard
    else
      regular_user_dashboard
    end
  end

  private
    def user
      @user ||= if params[:id]
                  User.find(params[:id])
                else
                  current_user
                end
    end

    def admin_dashboard
      render 'admin'
    end

    def regular_user_dashboard
      if user.city.nil?
        if current_user == user
          redirect_to new_city_path
        else
          redirect_to root_path, notice: 'Usuário ainda não criou sua cidade'
        end
        return
      end
      @city = ResultsCalculator.new user.city
      @answer = user.answer_for(@problem)
      @result = @answer.try :result
    end

    def dashboard
      @problem = Problem.current
    end
end

app/views/users/admin.html.haml
%h1 Painel do Professor

%h2= Problem.model_name.human
- if @problem.present?
  %p= @problem.text
  = link_to t(:edit), edit_problem_path(@problem), class: 'btn'
  = link_to t(:list_answers, count: @problem.answers.count), answers_path(problem_id: @problem)
- else
  = link_to t(:create), new_problem_path, class: 'btn'

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
.row
  .span8
    %h2 Dashboard
    %p
      #{User.human_attribute_name(:name)}: #{@user.name}

    - if @problem.nil?
      %h3 Não há um #{Problem.model_name.human.downcase} no momento
    - else
      %h3 #{Problem.model_name.human} atual
      %p= @problem.text
      - if @answer.nil?
        -if can?(:create, can_answer)
          = link_to 'Responder', new_answer_path(problem_id: @problem), class: 'btn'
      - else
        %h4 Sua #{Answer.model_name.human.downcase}
        %p= @answer.text
        - if can?(:update, @answer)
          = link_to 'Editar resposta', edit_answer_path(@answer), class: 'btn'
        - if @result.present?
          %h4= Result.model_name.human
          - if @result.valid_answer
            = table_for [:delta_pollution, :delta_public_support, :delta_corporate_support, 
              :delta_balance].map {|attr| [Result.human_attribute_name(attr), @result.send(attr)] }
            - if @result.characteristics.any?
              %h5= City.human_attribute_name(:characteristics)
              = list_for(@result.characteristics)
          - else
            %h3= t(:invalid_answer)
          %h5= Result.human_attribute_name(:text)
          %p= @result.text
  - if @city.present?
    = render partial: 'cities/show', locals: { city: @city }