config/routes.rb
EnvironmentClassesGamification::Application.routes.draw do
  root :to => "users#show"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :problems, only: [:new, :create, :edit, :update]
  resources :answers, only: [:index, :new, :create, :edit, :update]
  resources :results, only: [:new, :create, :edit, :update]
  resources :cities, only: [:new, :create]

  get 'regras' => 'pages#regras'
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :answer

  validates :answer, presence: true

  serialize :characteristics, Array

  def characteristics=(value)
    super(if value.is_a? String then value.split(';').map(&:strip) else value end)
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:create, :show, :edit, :update, :destroy]
  before_action :set_answer, only: [:new, :create, :edit, :update]
  before_action :set_city, only: [:new, :create, :edit, :update]
  load_and_authorize_resource

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new(answer: @answer)
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    respond_to do |format|
      if @result.save
        format.html { redirect_to answers_url(problem_id: @result.answer.problem), notice: I18n.t('notice.success.create', model: Result.model_name.human) }
      else
        format.html { render action: 'new' }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to answers_url(problem_id: @result.answer.problem), notice: I18n.t('notice.success.update', model: Result.model_name.human) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result ||= if params[:id].present?
        Result.find(params[:id])
      elsif params[:result].present?
        Result.new(result_params)
      end
    end

    def set_answer
      id = params[:answer_id] || @result.try(:answer_id) || set_result.answer_id
      @answer ||= Answer.find(id)
    end

    def set_city
      @city = ResultsCalculator.new @answer.city
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:answer_id, :characteristics, :delta_pollution, :delta_public_support, :delta_corporate_support, :delta_balance, :text, :valid_answer)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.haml
.row
  .span8
    %h2= Problem.model_name.human
    %p= @answer.problem.text
    %h2= Answer.model_name.human
    %p= @answer.text
    = simple_form_for(@result) do |f|
      = f.error_notification

      .form-inputs
        = f.input :answer_id, as: :hidden
        = f.input :valid_answer, input_html: { 'data-toggle' => '#valid-answer' }
        #valid-answer
          = f.input :characteristics, hint: t('hint.result.characteristics'), input_html: { value: @result.characteristics.join("; "), class: 'input-xxlarge' }
          - [:delta_pollution, :delta_public_support, :delta_corporate_support, :delta_balance].each do |delta|
            = f.input delta, as: :range, input_html: { min: -5, max: 5 }
        = f.input :text, as: :text, input_html: { class: 'input-block-level' }

      .form-actions
        = f.button :submit
  = render partial: 'cities/show', locals: { city: @city }

app/views/results/edit.html.haml
%h1 Editando resultado

= render 'form'

= link_to t(:back), root_path

app/views/results/index.html.haml
%h1 Listing results

%table
  %tr
    %th Characteristics
    %th Delta pollution
    %th Delta public support
    %th Delta corporate support
    %th Delta balance
    %th Text
    %th Valid answer
    %th
    %th
    %th

  - @results.each do |result|
    %tr
      %td= result.characteristics
      %td= result.delta_pollution
      %td= result.delta_public_support
      %td= result.delta_corporate_support
      %td= result.delta_balance
      %td= result.text
      %td= result.valid_answer
      %td= link_to 'Show', result
      %td= link_to 'Edit', edit_result_path(result)
      %td= link_to 'Destroy', result, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Result', new_result_path

app/views/results/new.html.haml
%h1 Novo resultado

= render 'form'

= link_to t(:back), root_path

app/views/results/show.html.haml
%p#notice= notice

%p
  %b Characteristics:
  = @result.characteristics
%p
  %b Delta pollution:
  = @result.delta_pollution
%p
  %b Delta public support:
  = @result.delta_public_support
%p
  %b Delta corporate support:
  = @result.delta_corporate_support
%p
  %b Delta balance:
  = @result.delta_balance
%p
  %b Text:
  = @result.text
%p
  %b Valid answer:
  = @result.valid_answer

= link_to 'Edit', edit_result_path(@result)
\|
= link_to 'Back', results_path