config/routes.rb
EnvironmentClassesGamification::Application.routes.draw do
  root :to => "users#show"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :problems, only: [:new, :create, :edit, :update]
  resources :answers, only: [:index, :new, :create, :edit, :update]
  resources :results, only: [:new, :create, :edit, :update]
  resources :cities, only: [:new, :create]

  get 'regras' => 'pages#regras'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :city
  belongs_to :problem
  has_one :result

  validates :city, presence: true
  validates :problem, presence: true, uniqueness: { scope: :city }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :set_problem, only: [:index, :new, :edit, :update]
  load_and_authorize_resource except: [:index, :new, :create]

  # GET /answers
  # GET /answers.json
  def index
    @answers = @problem.answers
    authorize! :index, Answer
  end

  # GET /answers/new
  def new
    @answer = Answer.new(city: current_user.city, problem: @problem)
    authorize! :new, @answer
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    @answer.city = current_user.city
    @problem = @answer.problem

    authorize! :create, @answer

    respond_to do |format|
      if @answer.save
        format.html { redirect_to root_path, notice: I18n.t('notice.success.create', model: Answer.model_name.human) }
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        result = @answer.result
        if result.present? && !result.valid_answer
          result.destroy
        end
        format.html { redirect_to root_path, notice: I18n.t('notice.success.update', model: Answer.model_name.human) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def set_problem
      @problem = params[:problem_id] ? Problem.find(params[:problem_id]) : @answer.problem
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:text, :problem_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.haml
%h2= Problem.model_name.human
%p= @problem.text
= simple_form_for(@answer) do |f|
  = f.error_notification

  .form-inputs
    = f.input :problem_id, as: :hidden
    = f.input :text, as: :text, input_html: { class: 'input-xxlarge', rows: 6 }

  .form-actions
    = f.button :submit

app/views/answers/edit.html.haml
%h1 Editar #{Answer.model_name.human.downcase}

= render 'form'

= link_to t(:back), root_path

app/views/answers/index.html.haml
%h1 Listando respostas para o problema atual

%ul
  - @answers.each do |answer|
    %li.answer
      %span{ class: "#{answer.result.present? ? 'processed' : 'pendent'}" }= answer.city.name
      = link_to t(:show), "#answer_#{answer.id}", 'data-toggle' => 'collapse', class: 'btn'
      .collapse{id: "answer_#{answer.id}"}
        %p= answer.text
        - if answer.result.present?
          = link_to t(:edit_model, model: Result.model_name.human), edit_result_path(answer.result), class: 'btn'
        - else
          = link_to t(:give_result), new_result_path(answer_id: answer), class: 'btn'

%br
= link_to t(:back), root_path

app/views/answers/new.html.haml
%h1 Nova #{Answer.model_name.human.downcase}

= render 'form'

= link_to t(:back), root_path

app/views/answers/show.html.haml
%p#notice= notice

%p
  %b Text:
  = @answer.text

= link_to 'Edit', edit_answer_path(@answer)
\|
= link_to 'Back', answers_path